import {test} from 'node:test';
import assert from 'node:assert/strict';
import {answersSchema,generateDemo,resultSchema} from '../lib/ideas';
import {LocalQuota} from '../lib/quota';
const base={niche:'Бьюти',task:'Запись / заявки',audience:'Для моих клиентов',goal:'Экономить время',details:'Маникюр, часто отменяют запись в последний момент'};
test('Three valid distinct ideas reflect free text and all answers',()=>{const ideas=generateDemo(base);assert.equal(resultSchema.parse({ideas}).ideas.length,3);assert.equal(new Set(ideas.map(i=>i.name)).size,3);assert.equal(ideas[0].name,'Свободное окно');for(const i of ideas){assert.ok(i.description.includes(base.details));assert.ok(i.description.includes(base.audience));assert.ok(i.benefit.includes(base.goal));}});
test('Different niches and tasks select different useful scenarios',()=>{const blog=generateDemo({...base,niche:'Контент / блог',task:'Контент',details:'Пишу про путешествия'});const sales=generateDemo({...base,niche:'Товары / продажи',task:'Подбор товаров или услуг',details:'Продаю мебель'});assert.equal(blog[0].name,'Тема с поводом');assert.equal(sales[0].name,'Точно под тебя');assert.notDeepEqual(blog,sales);});
test('Other answers are supported and oversized inputs rejected',()=>{assert.ok(answersSchema.safeParse({...base,niche:'Приют для кошек'}).success);assert.ok(!answersSchema.safeParse({...base,details:'x'.repeat(1201)}).success);assert.ok(!answersSchema.safeParse({...base,niche:''}).success);});
test('Quota persists, stops at three, and resets on next day',()=>{const data=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{value:{getItem:(k:string)=>data.get(k)||null,setItem:(k:string,v:string)=>data.set(k,v)},configurable:true});const q=new LocalQuota();assert.equal(q.remaining(),3);assert.ok(q.consume());assert.equal(new LocalQuota().remaining(),2);assert.ok(q.consume());assert.ok(q.consume());assert.equal(q.consume(),false);assert.equal(q.remaining(),0);data.set('a-chto-esli:quota:v1',JSON.stringify({day:'2000-01-01',count:3}));assert.equal(q.remaining(),3);data.set('a-chto-esli:quota:v1','broken');assert.equal(q.remaining(),3);});
