'use client';
import { useEffect, useRef, useState } from 'react';
import { questions, type AnswerKey } from '../lib/questions';
import { type Answers, type Idea, resultSchema } from '../lib/ideas';
import { LocalQuota } from '../lib/quota';
import { VK_URL, VK_CONFIGURED } from '../lib/config';
type View='home'|'quiz'|'loading'|'results'|'limit';
function Spark(){return <svg viewBox="0 0 200 200" fill="currentColor" aria-hidden="true"><path d="M91 0H109L114 64L155 16L169 29L129 78L193 62L198 80L137 101L200 122L194 140L130 124L171 174L156 187L114 140L109 200H91L86 139L45 186L31 173L71 123L7 139L2 121L63 100L0 79L6 61L70 77L29 27L44 14L86 62Z"/></svg>}
const empty:Answers={niche:'',task:'',audience:'',goal:'',details:''};
const phrases=['Смотрим, что можно упростить…','Ищем полезные сценарии…','Отбрасываем скучные идеи…','Кажется, кое-что нашли…'];
export default function Home(){
 const [view,setView]=useState<View>('home'),[step,setStep]=useState(0),[answers,setAnswers]=useState<Answers>(empty),[choices,setChoices]=useState<Record<string,string>>({}),[ideas,setIdeas]=useState<Idea[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[remaining,setRemaining]=useState(3),[phrase,setPhrase]=useState(0),[mode,setMode]=useState('demo');
 const busy=useRef(false);const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{try{setRemaining(new LocalQuota().remaining());}catch{setError('Браузер блокирует сохранение данных. Разреши локальное хранилище, чтобы использовать бесплатные попытки.');}},[]);
 useEffect(()=>{if(view!=='home'){heading.current?.focus();window.scrollTo({top:0,behavior:'instant'});}},[view,step]);
 useEffect(()=>{if(view!=='loading')return;const timer=setInterval(()=>setPhrase(p=>Math.min(p+1,3)),800);return()=>clearInterval(timer);},[view]);
 function begin(){setError('');setNotice('');try{const left=new LocalQuota().remaining();setRemaining(left);setView(left?'quiz':'limit');setStep(0);}catch{setError('Для бесплатного лимита необходимо разрешить локальное хранилище в браузере.');}}
 function select(key:AnswerKey,value:string){setChoices(c=>({...c,[key]:value}));setAnswers(a=>({...a,[key]:value==='Другое'?'':value}));setError('');}
 async function generate(){if(busy.current)return;busy.current=true;setError('');setPhrase(0);
  try{if(!new LocalQuota().remaining()){setView('limit');return;}setView('loading');
   const [response]=await Promise.all([fetch('/api/ideas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(answers),signal:AbortSignal.timeout(35000)}),new Promise(r=>setTimeout(r,2800))]);
   const body=await response.json();if(!response.ok)throw new Error(body.error||'Не удалось получить идеи. Попробуй ещё раз.');const result=resultSchema.parse(body);
   const quota=new LocalQuota();if(!quota.consume()){setView('limit');return;}setRemaining(quota.remaining());setIdeas(result.ideas);setMode(body.mode);setView('results');
  }catch(e){setError(e instanceof Error&&e.name!=='TimeoutError'?e.message:'Не удалось связаться с сервисом. Попробуй ещё раз — попытка не списана.');setView('quiz');}finally{busy.current=false;}
 }
 function ideaText(i:Idea){return `${i.name}\n${i.description}\nКак работает: ${i.scenario}\nПольза: ${i.benefit}`;}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice('Идея скопирована. Можно отправить её друзьям!');}catch{setNotice('Копирование недоступно. Выдели текст карточки и скопируй вручную.');}}
 async function share(){const text=ideas.map(ideaText).join('\n\n');try{if(navigator.share)await navigator.share({title:'А что, если…',text});else await copy(text);}catch(e){if(!(e instanceof Error&&e.name==='AbortError'))await copy(text);}}
 function Contact({label='Хочу свой сервис →'}:{label?:string}){return <><a className="button wine" href={VK_URL} target="_blank" rel="noopener noreferrer" onClick={e=>{if(!VK_CONFIGURED){e.preventDefault();setNotice('Лена пока не добавила ссылку VK. Контакт появится здесь после настройки проекта.');}}}>{label}</a>{!VK_CONFIGURED&&<small className="contact-note">Ссылка на VK скоро появится</small>}</>}
 const question=questions[step];
 return <div className="site"><header className="header"><button className="wordmark" onClick={()=>{if(!busy.current){setView('home');setNotice('');}}} aria-label="На главную">а что, если<span>…</span></button><span className="header-note"><i/> маленький шаг к большой идее</span><span className="edition">IDEA LAB / 01</span></header>
 <main>
 {view==='home'&&<><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="line"/> ИДЕЯ НАЧИНАЕТСЯ С ТЕБЯ</div><h1>А что, если тебе<br className="desktop"/> уже есть что<br/> <em>автоматизировать?</em></h1><p className="intro">Ответь на несколько вопросов — и получи 3 идеи сервиса, который можно создать именно под тебя, твою работу или бизнес.</p><button className="button wine hero-cta" onClick={begin}>Найти мою идею <span>→</span></button><div className="hero-meta"><span>5 вопросов</span><b>·</b><span>пара минут</span><b>·</b><span>бесплатно</span></div></div><div className="art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="art-label">ВОЗМОЖНОСТИ БЛИЖЕ, ЧЕМ КАЖЕТСЯ</span><div className="spark"><Spark/></div><div className="floating float-top"><span className="tiny-dot"/> твоя повседневная задача</div><div className="floating float-bottom"><span>→</span> что-то по-настоящему полезное</div><span className="art-index">ОТ «А ВДРУГ» ДО «ВОТ ОНО»</span></div></section><section className="intro-strip"><span className="strip-star">✦</span><p>Без сложных терминов.<br/><strong>Только идеи, которые реально могут пригодиться.</strong></p><span className="strip-end">ТВОЙ ОПЫТ + НЕМНОГО ВООБРАЖЕНИЯ</span></section><section className="how"><div><span className="eyebrow">НЕ НУЖНО БЫТЬ РАЗРАБОТЧИКОМ</span><h2>У каждой рутины<br/>есть <em>другая сторона.</em></h2></div><div className="how-item"><span>01 / РАССКАЖИ</span><p>О своём деле и о том,<br/>что хочется упростить.</p></div><div className="how-item"><span>02 / ВДОХНОВИСЬ</span><p>Тремя идеями.<br/>Конкретно под твой запрос.</p></div><div className="how-item"><span>03 / ПРЕДСТАВЬ</span><p>Как одна из них<br/>могла бы стать твоим сервисом.</p></div></section></>}
 {view==='quiz'&&<section className="quiz shell"><div className="quiz-top"><span className="eyebrow">НЕМНОГО О ТЕБЕ</span><span className="step-count">{step+1} <span>из 5</span></span></div><div className="progress" role="progressbar" aria-valuemin={0} aria-valuemax={5} aria-valuenow={step+1} aria-label="Прогресс анкеты"><div style={{width:`${(step+1)*20}%`}}/></div><h1 ref={heading} tabIndex={-1}>{step===4?'Расскажи чуть подробнее':question.title}</h1><p className="hint">{step===4?'Самые интересные идеи часто прячутся в деталях. Этот шаг можно пропустить.':question.hint}</p><form onSubmit={e=>{e.preventDefault();if(step===4){void generate();}else if(answers[question.key].trim()){setStep(step+1);}else setError('Выбери вариант или напиши свой ответ.');}}>
 {step<4?<><div className="options" role="group" aria-label={question.title}>{question.options.map((option,index)=><button key={option} type="button" className={`option ${choices[question.key]===option?'selected':''}`} aria-pressed={choices[question.key]===option} onClick={()=>select(question.key,option)}><span className="option-number">{String(index+1).padStart(2,'0')}</span>{option}<span className="option-check">{choices[question.key]===option?'✓':'+'}</span></button>)}</div>{choices[question.key]==='Другое'&&<label className="custom">Твой вариант<input autoFocus maxLength={180} value={answers[question.key]} onChange={e=>setAnswers(a=>({...a,[question.key]:e.target.value}))} placeholder="Расскажи своими словами" required/></label>}</>:<label className="details-label">Твоя ситуация<textarea maxLength={1200} value={answers.details} onChange={e=>setAnswers(a=>({...a,details:e.target.value}))} placeholder="Например: каждый день отвечаю клиентам на одни и те же вопросы / долго придумываю посты / хочу упростить запись клиентов."/><span className="text-count">{answers.details.length} / 1200</span></label>}
 {error&&<p className="error" role="alert">{error}</p>}<div className="quiz-actions"><button type="button" className="text-button" onClick={()=>step?setStep(step-1):setView('home')}>← Назад</button><button type="submit" className="button wine" disabled={step<4&&!answers[question.key].trim()}>{step===4?'Придумать 3 идеи ✦':'Дальше →'}</button></div><p className="privacy">Ответы используются для генерации идей. {remaining} из 3 бесплатных попыток на сегодня.</p></form></section>}
 {view==='loading'&&<section className="loading shell" aria-busy="true"><div className="loading-art" aria-hidden="true"><Spark/></div><span className="eyebrow">СОЕДИНЯЕМ ТОЧКИ</span><h1 ref={heading} tabIndex={-1} aria-live="polite">{phrases[phrase]}</h1><p>Твоё дело. Твоя задача. Твои возможности.</p><div className="loading-dots"><i/><i/><i/></div></section>}
 {view==='results'&&<section className="results"><div className="result-heading"><span className="eyebrow">А ВОТ И ТВОИ ВОЗМОЖНОСТИ</span><h1 ref={heading} tabIndex={-1}>Вот что можно<br/>создать <em>для тебя.</em></h1><p>Мы собрали 3 идеи на основе твоих ответов.</p><span className="mode-label">{mode==='demo'?'DEMO MODE · идеи без подключения AI':'AI · персональная подборка'}</span></div><div className="answer-summary"><span>{answers.niche}</span><span>{answers.task}</span><span>{answers.goal}</span></div><div className="idea-grid">{ideas.map((idea,index)=><article className="idea-card" key={idea.name}><div className="idea-top"><span>ИДЕЯ / 0{index+1}</span><span>→</span></div><h2>{idea.name}</h2><p className="idea-description">{idea.description}</p><div className="idea-section"><span>КАК РАБОТАЕТ</span><p>{idea.scenario}</p></div><div className="idea-section"><span>ЗАЧЕМ НУЖЕН</span><p>{idea.benefit}</p></div><div className="card-bottom"><span className="complexity">{idea.complexity}</span><button className="copy" onClick={()=>void copy(ideaText(idea))} aria-label={`Скопировать идею ${idea.name}`}>Скопировать →</button></div></article>)}</div><div className="result-actions"><button className="button outline" onClick={begin}>Попробовать ещё раз ↻</button><button className="text-button" onClick={()=>void share()}>Поделиться подборкой →</button><span className="remaining">Осталось попыток сегодня: {remaining}</span></div><section className="contact"><span className="contact-spark" aria-hidden="true"><Spark/></span><div><span className="eyebrow">ОТ ИДЕИ К РЕАЛЬНОСТИ</span><h2>А что, если такую идею<br/>действительно <em>запустить?</em></h2><p>Я создаю сайты, мини-приложения и AI-сервисы под конкретные задачи. Если одна из идей тебе откликнулась — можем обсудить, как превратить её в рабочий сервис.</p><Contact/></div></section></section>}
 {view==='limit'&&<section className="limit shell"><span className="limit-spark" aria-hidden="true"><Spark/></span><span className="eyebrow">ИДЕЙ УЖЕ ЦЕЛАЯ КОЛЛЕКЦИЯ</span><h1 ref={heading} tabIndex={-1}>Похоже, ты уже нашёл достаточно идей на сегодня :)</h1><p>Если хочется создать что-то своё — напиши мне, и мы подумаем над сервисом уже под твою задачу.</p><Contact label="Обсудить идею →"/><small>Три новые попытки появятся завтра. Лимит действует в этом браузере.</small>{ideas.length>0&&<button className="text-button" onClick={()=>setView('results')}>← Вернуться к идеям</button>}</section>}
 {view==='home'&&error&&<p className="error shell" role="alert">{error}</p>}
 </main>{notice&&<div className="toast" role="status"><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Закрыть уведомление">×</button></div>}<footer><span>А что, если…</span><span>С маленькой идеи начинается что-то большое.</span><small>created by Lena</small></footer></div>
}
